version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: mi-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mi_app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mi-app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: mi-app-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@miapp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mi-app-network

  # Opcional: Agregar Redis si la aplicación lo utiliza
  # redis:
  #   image: redis:alpine
  #   container_name: mi-app-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - mi-app-network

networks:
  mi-app-network:
    driver: bridge

volumes:
  pgdata: 